replicaCount: 1

image:
  repository: ghcr.io/olivecasazza/athena
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
metrics:
  enabled: true
  port: 8080
  serviceMonitor:
    enabled: true
    interval: 15s

observability:
  grafanaDashboard:
    enabled: true

serviceAccount:
  create: true
  name: "athena-operator"

auth:
  oidc:
    enabled: true
    issuerURL: "https://auth.casazza.io/realms/master"
    usernameClaim: "email"
    groupsClaim: "groups"
    adminGroup: "athena:admin"
    operatorGroup: "athena:operator"
    viewerGroup: "athena:viewer"
  rbac:
    create: true
    adminClusterRoleName: "athena-admin"
    operatorClusterRoleName: "athena-operator-role"
    adminGroupName: "athena:admin"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
