apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: athena
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: athena
    app.kubernetes.io/version: 0.1.10
    helm.sh/chart: athena-0.1.10
  name: athena
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: athena
      app.kubernetes.io/name: athena
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: athena
        app.kubernetes.io/name: athena
    spec:
      containers:
        - env:
            - name: METRICS_PORT
              value: '8080'
            - name: ATHENA_ADMIN_GROUP
              value: athena:admin
            - name: ATHENA_OPERATOR_GROUP
              value: athena:operator
          image: {{ printf "%s:%s" .Values.image.repository (.Values.image.tag | default "latest") | quote }}
          imagePullPolicy: IfNotPresent
          name: athena
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: athena-operator
