apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: athena
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: athena
    app.kubernetes.io/version: 0.1.10
    helm.sh/chart: athena-0.1.11
  name: athena
spec:
  endpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: athena
      app.kubernetes.io/name: athena
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/instance: athena
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: athena
    app.kubernetes.io/version: 0.1.10
    helm.sh/chart: athena-0.1.11
  name: athena-experiments
spec:
  podMetricsEndpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: athena-experiment
