{{- if .Values.auth.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.auth.rbac.adminClusterRoleName | quote }}
  labels:
{{ include "athena.labels" . | indent 4 }}
rules:
  - apiGroups: ["research.nixlab.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.auth.rbac.operatorClusterRoleName | quote }}
  labels:
{{ include "athena.labels" . | indent 4 }}
rules:
  - apiGroups: ["research.nixlab.io"]
    resources: ["runtimeprofiles", "experimenttemplates", "researchcampaigns", "experiments", "benchmarksuites", "benchmarkruns", "metricsources"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["research.nixlab.io"]
    resources: ["runtimeprofiles/status", "experimenttemplates/status", "researchcampaigns/status", "experiments/status", "benchmarksuites/status", "benchmarkruns/status", "metricsources/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "athena.fullname" . }}-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.auth.rbac.operatorClusterRoleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "athena.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "athena.fullname" . }}-admin-group-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.auth.rbac.adminClusterRoleName | quote }}
subjects:
  - kind: Group
    name: {{ .Values.auth.rbac.adminGroupName | quote }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "athena.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "athena.labels" . | indent 4 }}
{{- end }}
