apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: athena
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: athena
    app.kubernetes.io/version: 0.1.10
    helm.sh/chart: athena-0.1.11
  name: athena-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: athena
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: athena
    app.kubernetes.io/version: 0.1.10
    helm.sh/chart: athena-0.1.11
  name: athena-admin
rules:
  - apiGroups:
      - research.nixlab.io
    resources:
      - runtimeprofiles
      - experimenttemplates
      - researchcampaigns
      - experiments
      - benchmarksuites
      - benchmarkruns
      - metricsources
      - researchreports
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: athena
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: athena
    app.kubernetes.io/version: 0.1.10
    helm.sh/chart: athena-0.1.11
  name: athena-operator-role
rules:
  - apiGroups:
      - research.nixlab.io
    resources:
      - runtimeprofiles
      - experimenttemplates
      - researchcampaigns
      - experiments
      - benchmarksuites
      - benchmarkruns
      - metricsources
      - researchreports
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - research.nixlab.io
    resources:
      - benchmarkruns
      - experiments
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - research.nixlab.io
    resources:
      - researchreports
    verbs:
      - create
      - update
      - patch
  - apiGroups:
      - research.nixlab.io
    resources:
      - runtimeprofiles/status
      - experimenttemplates/status
      - researchcampaigns/status
      - experiments/status
      - benchmarksuites/status
      - benchmarkruns/status
      - metricsources/status
      - researchreports/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
      - events
      - configmaps
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ray.io
    resources:
      - rayjobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: athena-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: athena-operator-role
subjects:
  - kind: ServiceAccount
    name: athena-operator
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: athena-admin-group-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: athena-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: athena:admin
