name: Publish

on:
  push:
    branches:
      - main
      - feat/athena-operator-status
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello"
